// <auto-generated />
using Bank_WebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank_WebAPI.Migrations
{
    [DbContext(typeof(BankDBContext))]
    partial class BankDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bank_WebAPI.Models.b_savings", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("credit_amount")
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("b_Savings");
                });

            modelBuilder.Entity("Bank_WebAPI.Models.b_transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("credit_amount")
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal>("debit_amount")
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("tf_userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("b_Transactions");
                });

            modelBuilder.Entity("Bank_WebAPI.Models.b_user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password_salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pin_salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("b_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
